version: "3.8"
services:
  backend:
    build:
      context: ./backend
    container_name: notatnik_backend
    volumes:
      - ./backend/data:/data
    ports:
      - "8000:8000"
    networks:
      - notatniknet

  frontend:
    build:
      context: ./frontend
    container_name: notatnik_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - notatniknet

networks:
  notatniknet:
    driver: bridge
