apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: notatnik-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notatnik-backend
  template:
    metadata:
      labels:
        app: notatnik-backend
    spec:
      containers:
        - name: backend
          image: notatnik_backend:ci
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000